=== RatJuggler/great-pyramid-puzzle/src/puzzle-data-schema.json
{
  "$id": "https://pyramid.puzzle/pyramid-puzzle-data-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "The Great Pyramid Puzzle",
  "description": "Define the tile positions and tiles used in the Pyramid Puzzles.",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "puzzle", "numberOfTilesPerFace", "totalNumberOfTiles", "faces", "tiles"
  ],
  "properties": {
    "puzzle": {
      "description": "The name of this version of the Pyramid Puzzle.",
      "type": "string"
    },
    "numberOfTilesPerFace": {
      "description": "The number of tiles used on each face of the puzzle.",
      "type": "number"
    },
    "totalNumberOfTiles": {
      "description": "The total number of tiles used on the puzzle.",
      "type": "number"
    },
    "faces": {
      "description": "The faces of the tetrahedron.",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
         "additionalProperties": false,
        "properties": {
          "name": {
            "description": "The name of a face on the tetrahedron.",
            "type": "string"
          },
          "joins": {
            "description": "How a face joins with other faces on the tetrahedron.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "object",
               "additionalProperties": false,
              "properties": {
                "fromSide": {
                  "description": "The side of this face...",
                  "type": "string"
                },
                "toSide": {
                  "description": "Connects to this side...",
                  "type": "string"
                },
                "ofFace": {
                  "description": "Of this face.",
                  "type": "string"
                }
              }
            }
          },
          "tilePositions": {
            "description": "How tiles are positioned on a face.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "object",
               "additionalProperties": false,
              "properties": {
                "position": {
                  "description": "Tile position identifier",
                  "type": "string"
                },
                "joins": {
                  "description": "How a tile joins with other tiles on the tetrahedron.",
                  "type": "array",
                  "uniqueItems": true,
                  "items": {
                    "type": "object",
                     "additionalProperties": false,
                    "properties": {
                      "fromSide": {
                        "description": "The side of the tile at this position...",
                        "type": "string"
                      },
                      "toSide": {
                        "description": "Connects to this side...",
                        "type": "string"
                      },
                      "ofTilePosition": {
                        "description": "Of this tile position...",
                        "type": "string"
                      },
                      "onFace": {
                        "description": "On this face.",
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "tiles": {
      "description": "The tiles used by the version of the puzzle.",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
         "additionalProperties": false,
        "properties": {
          "tile": {
            "description": "A number to identify the individual tile.",
            "type": "string"
          },
          "sideA": {
            "description": "A string representing the pattern on side one of the tile (Seg1, Seg2, Seg3, Seg4)",
            "type": "string"
          },
          "sideB": {
            "description": "A string representing the pattern on side two of the tile (Seg5, Seg6, Seg7, Seg8).",
            "type": "string"
          },
          "sideC": {
            "description": "A string representing the pattern on side three of the tile (Seg9, Seg10, Seg11, Seg12).",
            "type": "string"
          }
        }
      }
    }
  }
}

=== RatJuggler/great-pyramid-puzzle/src/test-puzzle-data.json
{
  "puzzle": "test",
  "numberOfTilesPerFace": 1,
  "totalNumberOfTiles": 4,
  "faces": [
    {
      "name": "1",
      "joins": [
        {
          "fromSide": "A",
          "toSide": "B",
          "ofFace": "3"
        },
        {
          "fromSide": "B",
          "toSide": "B",
          "ofFace": "4"
        },
        {
          "fromSide": "C",
          "toSide": "B",
          "ofFace": "2"
        }
      ],
      "tilePositions": [
        {
          "position": "1",
          "joins": [
            {
              "fromSide": "A",
              "toSide": "B",
              "ofTilePosition": "1",
              "onFace": "3"
            },
            {
              "fromSide": "B",
              "toSide": "B",
              "ofTilePosition": "1",
              "onFace": "4"
            },
            {
              "fromSide": "C",
              "toSide": "B",
              "ofTilePosition": "1",
              "onFace": "2"
            }
          ]
        }
      ]
    },
    {
      "name": "2",
      "joins": [
        {
          "fromSide": "A",
          "toSide": "C",
          "ofFace": "3"
        },
        {
          "fromSide": "B",
          "toSide": "C",
          "ofFace": "1"
        },
        {
          "fromSide": "C",
          "toSide": "A",
          "ofFace": "4"
        }
      ],
      "tilePositions": [
        {
          "position": "1",
          "joins": [
            {
              "fromSide": "A",
              "toSide": "C",
              "ofTilePosition": "1",
              "onFace": "3"
            },
            {
              "fromSide": "B",
              "toSide": "C",
              "ofTilePosition": "1",
              "onFace": "1"
            },
            {
              "fromSide": "C",
              "toSide": "A",
              "ofTilePosition": "1",
              "onFace": "4"
            }
          ]
        }
      ]
    },
    {
      "name": "3",
      "joins": [
        {
          "fromSide": "A",
          "toSide": "C",
          "ofFace": "4"
        },
        {
          "fromSide": "B",
          "toSide": "A",
          "ofFace": "1"
        },
        {
          "fromSide": "C",
          "toSide": "A",
          "ofFace": "2"
        }
      ],
      "tilePositions": [
        {
          "position": "1",
          "joins": [
            {
              "fromSide": "A",
              "toSide": "C",
              "ofTilePosition": "1",
              "onFace": "4"
            },
            {
              "fromSide": "B",
              "toSide": "A",
              "ofTilePosition": "1",
              "onFace": "1"
            },
            {
              "fromSide": "C",
              "toSide": "A",
              "ofTilePosition": "1",
              "onFace": "2"
            }
          ]
        }
      ]
    },
    {
      "name": "4",
      "joins": [
        {
          "fromSide": "A",
          "toSide": "C",
          "ofFace": "2"
        },
        {
          "fromSide": "B",
          "toSide": "B",
          "ofFace": "1"
        },
        {
          "fromSide": "C",
          "toSide": "A",
          "ofFace": "3"
        }
      ],
      "tilePositions": [
        {
          "position": "1",
          "joins": [
            {
              "fromSide": "A",
              "toSide": "C",
              "ofTilePosition": "1",
              "onFace": "2"
            },
            {
              "fromSide": "B",
              "toSide": "B",
              "ofTilePosition": "1",
              "onFace": "1"
            },
            {
              "fromSide": "C",
              "toSide": "A",
              "ofTilePosition": "1",
              "onFace": "3"
            }
          ]
        }
      ]
    }
  ],
  "tiles": [
    {
      "tile": "1",
      "sideA": "1010",
      "sideB": "0010",
      "sideC": "0010"
    },
    {
      "tile": "2",
      "sideA": "0100",
      "sideB": "0100",
      "sideC": "1001"
    },
    {
      "tile": "3",
      "sideA": "0101",
      "sideB": "1001",
      "sideC": "1010"
    },
    {
      "tile": "4",
      "sideA": "0010",
      "sideB": "0100",
      "sideC": "0101"
    }
  ]
}
